services:
    transmission:    
        image: rettoph/transmission-openvpn 
        container_name: transmission
        volumes:
            #- /mnt/data:/mnt/data
            - /root/yar/openvpn:/etc/openvpn/custom
            #- /root/yar/config/transmission:/config
        environment:
            - PUID=1001
            - PGID=1002
            - CREATE_TUN_DEVICE=true
            - OPENVPN_PROVIDER=custom
            - OPENVPN_CONFIG=xx-yy-zz.protonvpn.udp
            - OPENVPN_USERNAME={USERNAME}+pmp
            - OPENVPN_PASSWORD={PASSWORD}
            - WEBPROXY_ENABLED=false
            - TRANSMISSION_DOWNLOAD_DIR=/mnt/data/downloads
            - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=false
            - TRANSMISSION_SEED_QUEUE_ENABLED=true
            - TRANSMISSION_INCOMPLETE_DIR_ENABLED=false
            - TRANSMISSION_PORT_FORWARDING_ENABLED=true
            - LOCAL_NETWORK=192.168.0.0/24
            - TZ=America/Boise
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        restart: unless-stopped